import { Person, Event } from '@/types';

export interface AutoEventConfig {
  type: 'birthday' | 'work-anniversary' | 'custom';
  title: string;
  defaultBudget: number;
  description?: string;
}

// Configuration des événements automatiques
const AUTO_EVENT_CONFIGS: Record<string, AutoEventConfig> = {
  birthday: {
    type: 'birthday',
    title: 'Anniversaire',
    defaultBudget: 50,
    description: 'Anniversaire annuel généré automatiquement'
  }
};

/**
 * Génère la prochaine occurrence d'un anniversaire
 */
const getNextBirthday = (birthdayString: string): Date => {
  console.log(`🎂 Calcul anniversaire pour: ${birthdayString}`);
  
  // Parsing de la date d'anniversaire
  const birthday = new Date(birthdayString);
  console.log(`Date d'origine parsée:`, birthday);
  
  const today = new Date();
  const currentYear = today.getFullYear();
  const todayStart = new Date(currentYear, today.getMonth(), today.getDate());
  
  // Créer la date d'anniversaire pour cette année (en heure locale)
  const thisYearBirthday = new Date(currentYear, birthday.getMonth(), birthday.getDate());
  console.log(`Anniversaire cette année:`, thisYearBirthday);
  
  // Si l'anniversaire de cette année est passé (en se basant sur le jour, pas l'heure)
  if (thisYearBirthday < todayStart) {
    const nextYear = new Date(currentYear + 1, birthday.getMonth(), birthday.getDate());
    console.log(`Anniversaire année prochaine:`, nextYear);
    return nextYear;
  }
  
  console.log(`Anniversaire retourné:`, thisYearBirthday);
  return thisYearBirthday;
};

/**
 * Génère des événements automatiques pour une personne
 */
export const generateAutoEventsForPerson = (person: Person, existingEvents: Event[]): Event[] => {
  const autoEvents: Event[] = [];
  
  // Génération d'événement anniversaire
  if (person.birthday) {
    console.log(`🎂 Génération anniversaire pour ${person.name} (${person.birthday})`);
    
    // Vérification plus robuste : chercher par personId, type ET année de l'événement
    const nextBirthday = getNextBirthday(person.birthday);
    const targetYear = nextBirthday.getFullYear();
    
    const existingBirthdayEvent = existingEvents.find(
      event => event.personId === person.id && 
               event.type === 'birthday' && 
               new Date(event.date).getFullYear() === targetYear
    );
    
    console.log(`Événement anniversaire existant pour ${targetYear}:`, existingBirthdayEvent ? 'OUI' : 'NON');
    
    // Si aucun événement anniversaire n'existe pour cette année, en créer un
    if (!existingBirthdayEvent) {
      console.log(`Prochain anniversaire calculé:`, nextBirthday);
      
      const birthdayEvent: Event = {
        id: `auto-birthday-${person.id}-${targetYear}`,
        title: `Anniversaire de ${person.name}`,
        person: person.name,
        personId: person.id,
        date: `${nextBirthday.getFullYear()}-${String(nextBirthday.getMonth() + 1).padStart(2, '0')}-${String(nextBirthday.getDate()).padStart(2, '0')}`,
        type: 'birthday',
        budget: person.budget || AUTO_EVENT_CONFIGS.birthday.defaultBudget,
        description: `🎂 Événement généré automatiquement - ${getAge(person.birthday, nextBirthday)} ans`,
        status: 'upcoming',
        isAutoGenerated: true
      };
      
      console.log(`✅ Événement anniversaire créé:`, birthdayEvent);
      autoEvents.push(birthdayEvent);
    }
  }
  
  return autoEvents;
};

/**
 * Calcule l'âge à une date donnée
 */
const getAge = (birthdayString: string, targetDate: Date): number => {
  const birthday = new Date(birthdayString);
  let age = targetDate.getFullYear() - birthday.getFullYear();
  const monthDiff = targetDate.getMonth() - birthday.getMonth();
  
  if (monthDiff < 0 || (monthDiff === 0 && targetDate.getDate() < birthday.getDate())) {
    age--;
  }
  
  return age;
};

/**
 * Met à jour les événements automatiques pour tous les profils
 */
export const updateAllAutoEvents = (persons: Person[], existingEvents: Event[]): Event[] => {
  const autoEvents: Event[] = [];
  
  persons.forEach(person => {
    const personAutoEvents = generateAutoEventsForPerson(person, existingEvents);
    autoEvents.push(...personAutoEvents);
  });
  
  return autoEvents;
};

/**
 * Régénère les événements anniversaire pour l'année suivante
 */
export const regenerateYearlyEvents = (persons: Person[], existingEvents: Event[]): Event[] => {
  const newEvents: Event[] = [];
  const currentYear = new Date().getFullYear();
  
  persons.forEach(person => {
    if (person.birthday) {
      // Créer l'événement pour l'année prochaine si pas déjà existant
      const nextYearEventId = `auto-birthday-${person.id}-${currentYear + 1}`;
      const nextYearExists = existingEvents.some(event => event.id === nextYearEventId);
      
      if (!nextYearExists) {
        const nextYearBirthday = new Date(currentYear + 1, new Date(person.birthday).getMonth(), new Date(person.birthday).getDate());
        
        const birthdayEvent: Event = {
          id: nextYearEventId,
          title: `Anniversaire de ${person.name}`,
          person: person.name,
          personId: person.id,
          date: `${nextYearBirthday.getFullYear()}-${String(nextYearBirthday.getMonth() + 1).padStart(2, '0')}-${String(nextYearBirthday.getDate()).padStart(2, '0')}`,
          type: 'birthday',
          budget: person.budget || AUTO_EVENT_CONFIGS.birthday.defaultBudget,
          description: `🎂 Événement généré automatiquement - ${getAge(person.birthday, nextYearBirthday)} ans`,
          status: 'upcoming',
          isAutoGenerated: true
        };
        
        newEvents.push(birthdayEvent);
      }
    }
  });
  
  return newEvents;
};