// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uurlvbvsewzshbppcfrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1cmx2YnZzZXd6c2hicHBjZnJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczOTk4NTIsImV4cCI6MjA3Mjk3NTg1Mn0.a7MDxaE59QYujeLhRr8GlLZ_LI2rNvAjNVmbxdKRjbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});